#!/usr/bin/env python3


import argparse
import requests
import json


base_url = 'http://taprepo.pythonanywhere.com'
Headers = { "Authorization" : "Basic YmFkc2VjdG9yOkJzaXRQQ04="}
def get_all_parameters():
    response = requests.get(f'{base_url}/parameters/', headers=Headers)
    return [param['name'] for param in response.json()]

def get_top_parameters(top):
    response = requests.get(f'{base_url}/parameters/get_top', params={'top': top}, headers=Headers)
    return [param['name'] for param in response.json()]

def get_parameters_by_type(type_name):
    response = requests.get(f'{base_url}/parameters/get_by_type', params={'type': type_name}, headers=Headers)
    return [param['name'] for param in response.json()]

def add_parameter(name, type=None, site=None):
    data = {'name': name, 'type': type, 'site': site}
    data = {k: v for k, v in data.items() if v is not None}
    response = requests.post(f'{base_url}/parameters/', data=json.dumps(data), headers=Headers+{'Content-Type': 'application/json'})
    return response.json()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Interact with parameters API.')
    parser.add_argument('--all', action='store_true', help='Get all parameters')
    parser.add_argument('--top', type=int, help='Get top parameters')
    parser.add_argument('--type', type=str, help='Get/Set parameters type')
    parser.add_argument('--add', action='store_true', help='Add a new parameter')
    parser.add_argument('--name', type=str, help='Name of the parameter to add')
    parser.add_argument('--types', type=str, help='Types of the parameter to add')
    parser.add_argument('--site', type=str, help='Site of the parameter is used')

    args = parser.parse_args()

    if args.all:
        for parameter in get_all_parameters():
            print(parameter)
    elif args.top:
        for parameter in get_top_parameters(args.top):
            print(parameter)
    elif args.add:
        if args.name :
            type = args.type if args.type else None
            site = args.site if args.site else None
            print(add_parameter(args.name, type, site))
        else:
            print("You must provide --name when adding a parameter.")
    elif args.type:
        for parameter in get_parameters_by_type(args.type):
            print(parameter)
