# Generated by Django 5.0.4 on 2024-05-02 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Parameter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='types',
            new_name='type',
        ),
    ]
