# Generated by Django 5.0.4 on 2024-05-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parameter', '0002_rename_types_parameter_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameter',
            options={'ordering': ['-count']},
        ),
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='type',
            field=models.ManyToManyField(blank=True, to='Parameter.type'),
        ),
    ]
