# Generated by Django 5.0.4 on 2024-05-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parameter', '0003_alter_parameter_options_alter_parameter_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='parameter',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='parameter',
            name='site',
            field=models.ManyToManyField(blank=True, to='Parameter.site'),
        ),
    ]
